#!/usr/bin/env python
"""Test log level system"""

from archiverr.utils.debug import init_debugger, LogLevel

print("=" * 60)
print("TESTING LOG LEVEL SYSTEM")
print("=" * 60)
print()

# Test 1: DEBUG level (show everything)
print("TEST 1: DEBUG Level (should show ALL)")
print("-" * 60)
debugger = init_debugger(level='DEBUG')
debugger.debug("test", "This is DEBUG")
debugger.info("test", "This is INFO")
debugger.warning("test", "This is WARNING")
debugger.error("test", "This is ERROR")
debugger.critical("test", "This is CRITICAL")
print()

# Test 2: INFO level (default, show INFO and above)
print("TEST 2: INFO Level (should show INFO, WARNING, ERROR, CRITICAL)")
print("-" * 60)
debugger = init_debugger(level='INFO')
debugger.debug("test", "This is DEBUG - SHOULD NOT SHOW")
debugger.info("test", "This is INFO")
debugger.warning("test", "This is WARNING")
debugger.error("test", "This is ERROR")
debugger.critical("test", "This is CRITICAL")
print()

# Test 3: WARNING level (show only warnings and errors)
print("TEST 3: WARNING Level (should show WARNING, ERROR, CRITICAL)")
print("-" * 60)
debugger = init_debugger(level='WARNING')
debugger.debug("test", "This is DEBUG - SHOULD NOT SHOW")
debugger.info("test", "This is INFO - SHOULD NOT SHOW")
debugger.warning("test", "This is WARNING")
debugger.error("test", "This is ERROR")
debugger.critical("test", "This is CRITICAL")
print()

# Test 4: ERROR level (show only errors)
print("TEST 4: ERROR Level (should show ERROR, CRITICAL)")
print("-" * 60)
debugger = init_debugger(level='ERROR')
debugger.debug("test", "This is DEBUG - SHOULD NOT SHOW")
debugger.info("test", "This is INFO - SHOULD NOT SHOW")
debugger.warning("test", "This is WARNING - SHOULD NOT SHOW")
debugger.error("test", "This is ERROR")
debugger.critical("test", "This is CRITICAL")
print()

print("=" * 60)
print("✅ LOG LEVEL SYSTEM TEST COMPLETE")
print("=" * 60)
