"""
State Models - Session 12 Refactored

Models:
- StateEnum
- InputData, OutputData
- JobStatus, RunStatus
- JobState, RunState
- PluginStatus, PluginState (Session 12)

Session 12 Changes:
- Plugin data structure: plugin.{name}.data.*
- PluginStatus with success flag
- JobState.plugins now has status + data separation
"""

from dataclasses import dataclass, field
from datetime import datetime
from typing import Dict, Any, List, Optional
from enum import Enum


class StateEnum(Enum):
    """
    Unified state enum for Run and Job states.
    
    Aligned with API schemas (Session 12/13 fix).
    """
    PENDING = "pending"
    RUNNING = "running"
    SUCCESS = "success"  # Was COMPLETED (aligned with API)
    FAILED = "failed"
    PARTIAL = "partial"  # New: for partial success
    CANCELLED = "cancelled"  # New: for cancelled runs


@dataclass
class InputData:
    """
    job input data container.
    
    attributes:
        value: input path or virtual identifier
        data: additional metadata (filename, extension, size_bytes, etc.)
        metadata: tracking info (filled_by, filled_at)
    """
    value: str
    data: Dict[str, Any] = field(default_factory=dict)
    metadata: Dict[str, Any] = field(default_factory=dict)  # filled_by, filled_at
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "value": self.value,
            "data": self.data,
            "metadata": self.metadata
        }


@dataclass
class OutputData:
    """
    job output data container.
    
    attributes:
        values: list of output paths generated by tasks
        data: task execution results and metadata
        metadata: tracking info (filled_by, filled_at)
    """
    values: List[str] = field(default_factory=list)
    data: Dict[str, Any] = field(default_factory=dict)
    metadata: Dict[str, Any] = field(default_factory=dict)  # filled_by, filled_at
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "values": self.values,
            "data": self.data,
            "metadata": self.metadata
        }


@dataclass
class JobStatus:
    """
    Job execution status.
    """
    state: StateEnum = StateEnum.PENDING
    success: bool = True
    executed: List[str] = field(default_factory=list)
    failed: List[str] = field(default_factory=list)
    skipped: List[str] = field(default_factory=list)
    started_at: Optional[datetime] = None
    finished_at: Optional[datetime] = None
    duration_ms: int = 0
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "state": self.state.value,
            "success": self.success,
            "executed": self.executed,
            "failed": self.failed,
            "skipped": self.skipped,
            "started_at": self.started_at.isoformat() if self.started_at else None,
            "finished_at": self.finished_at.isoformat() if self.finished_at else None,
            "duration_ms": self.duration_ms
        }


@dataclass
class RunStatus:
    """
    Run execution status.
    """
    state: StateEnum = StateEnum.PENDING
    success: bool = True
    total_jobs: int = 0
    completed: int = 0
    failed: int = 0
    started_at: Optional[datetime] = None
    finished_at: Optional[datetime] = None
    duration_ms: int = 0
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "state": self.state.value,
            "success": self.success,
            "total_jobs": self.total_jobs,
            "completed": self.completed,
            "failed": self.failed,
            "started_at": self.started_at.isoformat() if self.started_at else None,
            "finished_at": self.finished_at.isoformat() if self.finished_at else None,
            "duration_ms": self.duration_ms
        }


@dataclass
class JobState:
    """
    Per-job state.
    
    Session 11 structure:
    - input: InputData with value and data
    - output: OutputData with values and data
    - plugins: Dict for runtime plugin data access
    - status: JobStatus with executed/failed/skipped lists
    
    ID Format: job_{run_id}_{index}
    """
    index: int
    run_id: str
    id: str = field(default="")
    input: InputData = field(default_factory=lambda: InputData(""))
    output: OutputData = field(default_factory=OutputData)
    status: JobStatus = field(default_factory=JobStatus)
    plugins: Dict[str, Dict[str, Any]] = field(default_factory=dict)
    
    def __post_init__(self):
        if not self.id:
            self.id = f"job_{self.run_id}_{self.index}"
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "index": self.index,
            "run_id": self.run_id,
            "input": self.input.to_dict(),
            "output": self.output.to_dict(),
            "status": self.status.to_dict(),
            "plugins": self.plugins
        }
    
    def start(self):
        """Mark job as started."""
        self.status.state = StateEnum.RUNNING
        self.status.started_at = datetime.now()
    
    def complete(self, success: bool = True):
        """Mark job as completed."""
        self.status.finished_at = datetime.now()
        if self.status.started_at:
            delta = self.status.finished_at - self.status.started_at
            self.status.duration_ms = int(delta.total_seconds() * 1000)
        self.status.success = success
        self.status.state = StateEnum.SUCCESS if success else StateEnum.FAILED
    
    def add_executed(self, plugin_name: str):
        """Mark plugin as successfully executed."""
        if plugin_name not in self.status.executed:
            self.status.executed.append(plugin_name)
    
    def add_failed(self, plugin_name: str):
        """Mark plugin as failed."""
        if plugin_name not in self.status.failed:
            self.status.failed.append(plugin_name)
            self.status.success = False
    
    def add_skipped(self, plugin_name: str):
        """Mark plugin as skipped."""
        if plugin_name not in self.status.skipped:
            self.status.skipped.append(plugin_name)
    
    # Legacy compatibility properties
    @property
    def input_path(self) -> str:
        """Legacy: Get input path."""
        return self.input.value
    
    @property
    def execution_id(self) -> str:
        """Legacy: Get run ID."""
        return self.run_id
    
    @property
    def executed_plugins(self) -> List[str]:
        """Legacy: Get executed plugins."""
        return self.status.executed
    
    @property
    def failed_plugins(self) -> List[str]:
        """Legacy: Get failed plugins."""
        return self.status.failed
    
    @property
    def not_supported_plugins(self) -> List[str]:
        """Legacy: Get skipped plugins."""
        return self.status.skipped


@dataclass
class RunState:
    """
    Execution-level state.
    
    ID Format: run_{uuid8}
    """
    id: str
    status: RunStatus = field(default_factory=RunStatus)
    config: Dict[str, Any] = field(default_factory=dict)
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "status": self.status.to_dict(),
            "config": self.config
        }
    
    def start(self):
        """Mark run as started."""
        self.status.state = StateEnum.RUNNING
        self.status.started_at = datetime.now()
    
    def complete(self):
        """Mark run as completed."""
        self.status.finished_at = datetime.now()
        if self.status.started_at:
            delta = self.status.finished_at - self.status.started_at
            self.status.duration_ms = int(delta.total_seconds() * 1000)
        self.status.success = self.status.failed == 0
        self.status.state = StateEnum.SUCCESS if self.status.success else StateEnum.FAILED
    
    def increment_jobs(self):
        """Increment total job count."""
        self.status.total_jobs += 1
    
    def increment_completed(self):
        """Increment completed job count."""
        self.status.completed += 1
    
    def increment_failed(self):
        """Increment failed job count."""
        self.status.failed += 1


@dataclass
class PluginStatus:
    """
    Plugin execution status (Session 12).
    
    Tracks plugin execution state and success.
    """
    state: StateEnum = StateEnum.PENDING
    success: bool = False
    started_at: Optional[datetime] = None
    finished_at: Optional[datetime] = None
    duration_ms: int = 0
    error: Optional[str] = None
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "state": self.state.value,
            "success": self.success,
            "started_at": self.started_at.isoformat() if self.started_at else None,
            "finished_at": self.finished_at.isoformat() if self.finished_at else None,
            "duration_ms": self.duration_ms,
            "error": self.error
        }


@dataclass
class PluginState:
    """
    Session 12 plugin state structure.
    
    Structure:
        plugin.{name}:
            status: PluginStatus
            data: Dict (plugin's own data)
    """
    status: PluginStatus = field(default_factory=PluginStatus)
    data: Dict[str, Any] = field(default_factory=dict)
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "status": self.status.to_dict(),
            "data": self.data
        }


@dataclass
class PluginData:
    """
    Plugin execution data (stored in MongoDB).
    
    Session 12: Separates status and data.
    ID Format: plugin_{job_id}_{plugin_name}
    """
    job_id: str
    run_id: str
    job_index: int
    plugin_name: str
    stage: str  # parse | data | output (no input)
    status: PluginStatus = field(default_factory=PluginStatus)
    data: Dict[str, Any] = field(default_factory=dict)
    
    @property
    def id(self) -> str:
        return f"plugin_{self.job_id}_{self.plugin_name}"
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "job_id": self.job_id,
            "run_id": self.run_id,
            "job_index": self.job_index,
            "plugin_name": self.plugin_name,
            "stage": self.stage,
            "status": self.status.to_dict(),
            "data": self.data
        }


# NOTE: Legacy aliases (ExecutionStatus, MatchState, ExecutionState, PluginResult)
# are now defined in __init__.py for cleaner module structure.
# Direct imports from models.py should use the new names:
#   - StateEnum (not ExecutionStatus)
#   - JobState (not MatchState)
#   - RunState (not ExecutionState)
